//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwsFrame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EwsFrame.MailConfig", typeof(MailConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;&quot;&gt;
        ///	&lt;span style=&quot;color:#1F497D&quot;&gt;[{1}]&amp;nbsp;
        ///		&lt;a href=&quot;{0}&quot; style=&quot;color: rgb(5, 99, 193); text-decoration: underline;&quot; &gt;
        ///			{0}
        ///		&lt;/a&gt;
        ///	&lt;/span&gt;
        ///&lt;/p&gt;
        ///&lt;p style=&quot;margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;&quot;&gt;&lt;span style=&quot;color:#1F497D&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        internal static string HtmlBodyForRestoreUrlTemplate {
            get {
                return ResourceManager.GetString("HtmlBodyForRestoreUrlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;p style=&quot;margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;&quot;&gt;Dear Sir:&lt;/p&gt;
        ///&lt;p style=&quot;margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;&quot;&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p style=&quot;margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;&quot;&gt;Your restore job complete successfully.&lt;/p&gt;&lt;p style=&quot;margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;&quot;&gt;The restore result is compressed into {0} zip files, please download them from the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlBodyTemplate {
            get {
                return ResourceManager.GetString("HtmlBodyTemplate", resourceCulture);
            }
        }
    }
}
