//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInterop.EWSUtil.Setting.Internals {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ExceptionHResult : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExceptionHResult defaultInstance = ((ExceptionHResult)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExceptionHResult())));
        
        public static ExceptionHResult Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147483647")]
        public int AutodiscoverLocalException {
            get {
                return ((int)(this["AutodiscoverLocalException"]));
            }
            set {
                this["AutodiscoverLocalException"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147483646")]
        public int IOException {
            get {
                return ((int)(this["IOException"]));
            }
            set {
                this["IOException"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147483645")]
        public int AutodiscoverRemoteException {
            get {
                return ((int)(this["AutodiscoverRemoteException"]));
            }
            set {
                this["AutodiscoverRemoteException"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147483644")]
        public int ServiceValidationException {
            get {
                return ((int)(this["ServiceValidationException"]));
            }
            set {
                this["ServiceValidationException"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147483648")]
        public int OtherException {
            get {
                return ((int)(this["OtherException"]));
            }
            set {
                this["OtherException"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147483643")]
        public int ImportFTStreamFailed {
            get {
                return ((int)(this["ImportFTStreamFailed"]));
            }
            set {
                this["ImportFTStreamFailed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147483642")]
        public int CanntCreateFindFolder {
            get {
                return ((int)(this["CanntCreateFindFolder"]));
            }
            set {
                this["CanntCreateFindFolder"] = value;
            }
        }
    }
}
